
//  ******************************************************
// 
//     File generated by: neuroConstruct v1.5.2
// 
//  ******************************************************

*absolute
*cartesian
*asymmetric

*set_global	         RM	0.3333333

*set_global	         EREST_ACT	-0.07

*set_compt_param     ELEAK	-0.0594

*compt /library/compartment

*set_compt_param     RA 2.5
*set_compt_param     CM 0.009
*set_compt_param     ELEAK -0.0666
*set_compt_param     RM 5.0


*double_endpoint
Seg0_comp_1 none 0 0 0 0 12.5 0 18 naf__-2138440619 2000 ar__218603037 1 cad__-1909645461 -6.1304081E14 cal 16 cat 1 ka 200 kahp_deeppyr 2 kc 288 kdr 1700 km 85 nap 1.6 k2 5 
*double_endpoint_off

Seg1_comp_1 Seg0_comp_1 0 25 0 18 naf__-2138440619 2000 ar__218603037 1 cad__-1909645461 -6.1304081E14 cal 16 cat 1 ka 200 kahp_deeppyr 2 kc 288 kdr 1700 km 85 nap 1.6 k2 5 

*set_compt_param     RA 1.0
*set_compt_param     CM 0.018
*set_compt_param     ELEAK -0.0666
*set_compt_param     RM 0.1


*double_endpoint
Seg0_comp_56__Extra_0 Seg0_comp_1 0 0 0 2.083333 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 
*double_endpoint_off

Seg0_comp_56__Extra_1 Seg0_comp_56__Extra_0 4.166667 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_56__Extra_2 Seg0_comp_56__Extra_1 6.25 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_56__Extra_3 Seg0_comp_56__Extra_2 8.333334 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_56__Extra_4 Seg0_comp_56__Extra_3 10.41667 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_56 Seg0_comp_56__Extra_4 12.5 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg1_comp_56__Extra_0 Seg0_comp_56 14.58333 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg1_comp_56__Extra_1 Seg1_comp_56__Extra_0 16.66667 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg1_comp_56__Extra_2 Seg1_comp_56__Extra_1 18.75 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg1_comp_56__Extra_3 Seg1_comp_56__Extra_2 20.83333 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg1_comp_56__Extra_4 Seg1_comp_56__Extra_3 22.91667 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg1_comp_56 Seg1_comp_56__Extra_4 25 0 0 1.8 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

*set_compt_param     RA 2.5
*set_compt_param     ELEAK -0.0666
*set_compt_param     RM 0.33333334


Seg0_comp_35__Extra_0 Seg1_comp_1 0 28.40909 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303749E17 

Seg0_comp_35__Extra_1 Seg0_comp_35__Extra_0 0 31.81818 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303525E17 

Seg0_comp_35__Extra_2 Seg0_comp_35__Extra_1 0 35.22727 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg0_comp_35__Extra_3 Seg0_comp_35__Extra_2 0 38.63636 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303646E17 

Seg0_comp_35__Extra_4 Seg0_comp_35__Extra_3 0 42.04546 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303646E17 

Seg0_comp_35__Extra_5 Seg0_comp_35__Extra_4 0 45.45455 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303646E17 

Seg0_comp_35__Extra_6 Seg0_comp_35__Extra_5 0 48.86364 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg0_comp_35__Extra_7 Seg0_comp_35__Extra_6 0 52.27273 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303646E17 

Seg0_comp_35__Extra_8 Seg0_comp_35__Extra_7 0 55.68182 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303646E17 

Seg0_comp_35__Extra_9 Seg0_comp_35__Extra_8 0 59.09091 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303646E17 

Seg0_comp_35 Seg0_comp_35__Extra_9 0 62.5 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35__Extra_0 Seg0_comp_35 0 65.90909 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35__Extra_1 Seg1_comp_35__Extra_0 0 69.31818 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303405E17 

Seg1_comp_35__Extra_2 Seg1_comp_35__Extra_1 0 72.72728 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303405E17 

Seg1_comp_35__Extra_3 Seg1_comp_35__Extra_2 0 76.13637 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35__Extra_4 Seg1_comp_35__Extra_3 0 79.54546 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35__Extra_5 Seg1_comp_35__Extra_4 0 82.95454 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35__Extra_6 Seg1_comp_35__Extra_5 0 86.36364 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303405E17 

Seg1_comp_35__Extra_7 Seg1_comp_35__Extra_6 0 89.77273 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35__Extra_8 Seg1_comp_35__Extra_7 0 93.18182 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303405E17 

Seg1_comp_35__Extra_9 Seg1_comp_35__Extra_8 0 96.59091 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg1_comp_35 Seg1_comp_35__Extra_9 0 100 0 4 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.02303869E17 

Seg0_comp_6__Extra_0 Seg1_comp_1 0 23.61539 -1.846154 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6__Extra_1 Seg0_comp_6__Extra_0 0 22.23077 -3.692308 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6__Extra_2 Seg0_comp_6__Extra_1 0 20.84616 -5.538462 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319472E17 

Seg0_comp_6__Extra_3 Seg0_comp_6__Extra_2 0 19.46154 -7.384616 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6__Extra_4 Seg0_comp_6__Extra_3 0 18.07692 -9.230769 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319452E17 

Seg0_comp_6__Extra_5 Seg0_comp_6__Extra_4 0 16.69231 -11.07692 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6__Extra_6 Seg0_comp_6__Extra_5 0 15.30769 -12.92308 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319431E17 

Seg0_comp_6__Extra_7 Seg0_comp_6__Extra_6 0 13.92308 -14.76923 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6__Extra_8 Seg0_comp_6__Extra_7 0 12.53846 -16.61539 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319486E17 

Seg0_comp_6__Extra_9 Seg0_comp_6__Extra_8 0 11.15385 -18.46154 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6__Extra_10 Seg0_comp_6__Extra_9 0 9.769231 -20.30769 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319438E17 

Seg0_comp_6__Extra_11 Seg0_comp_6__Extra_10 0 8.384615 -22.15385 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_6 Seg0_comp_6__Extra_11 0 7 -24 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319486E17 

Seg1_comp_6__Extra_0 Seg0_comp_6 0 5.615385 -25.84616 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319431E17 

Seg1_comp_6__Extra_1 Seg1_comp_6__Extra_0 0 4.230769 -27.69231 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319431E17 

Seg1_comp_6__Extra_2 Seg1_comp_6__Extra_1 0 2.846154 -29.53846 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319534E17 

Seg1_comp_6__Extra_3 Seg1_comp_6__Extra_2 0 1.461539 -31.38462 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319438E17 

Seg1_comp_6__Extra_4 Seg1_comp_6__Extra_3 0 0.07692289 -33.23077 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319562E17 

Seg1_comp_6__Extra_5 Seg1_comp_6__Extra_4 0 -1.307692 -35.07692 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.031939E17 

Seg1_comp_6__Extra_6 Seg1_comp_6__Extra_5 0 -2.692308 -36.92308 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg1_comp_6__Extra_7 Seg1_comp_6__Extra_6 0 -4.076923 -38.76923 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319383E17 

Seg1_comp_6__Extra_8 Seg1_comp_6__Extra_7 0 -5.461539 -40.61539 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg1_comp_6__Extra_9 Seg1_comp_6__Extra_8 0 -6.846154 -42.46154 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319596E17 

Seg1_comp_6__Extra_10 Seg1_comp_6__Extra_9 0 -8.230769 -44.30769 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319383E17 

Seg1_comp_6__Extra_11 Seg1_comp_6__Extra_10 0 -9.615384 -46.15385 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319486E17 

Seg1_comp_6 Seg1_comp_6__Extra_11 0 -11 -48 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_0 Seg1_comp_1 -1.846154 23.61539 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_1 Seg0_comp_5__Extra_0 -3.692308 22.23077 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_2 Seg0_comp_5__Extra_1 -5.538462 20.84616 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319472E17 

Seg0_comp_5__Extra_3 Seg0_comp_5__Extra_2 -7.384616 19.46154 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_4 Seg0_comp_5__Extra_3 -9.230769 18.07692 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319452E17 

Seg0_comp_5__Extra_5 Seg0_comp_5__Extra_4 -11.07692 16.69231 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_6 Seg0_comp_5__Extra_5 -12.92308 15.30769 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319431E17 

Seg0_comp_5__Extra_7 Seg0_comp_5__Extra_6 -14.76923 13.92308 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_8 Seg0_comp_5__Extra_7 -16.61539 12.53846 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319486E17 

Seg0_comp_5__Extra_9 Seg0_comp_5__Extra_8 -18.46154 11.15385 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5__Extra_10 Seg0_comp_5__Extra_9 -20.30769 9.769231 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319438E17 

Seg0_comp_5__Extra_11 Seg0_comp_5__Extra_10 -22.15385 8.384615 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_5 Seg0_comp_5__Extra_11 -24 7 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319486E17 

Seg1_comp_5__Extra_0 Seg0_comp_5 -25.84616 5.615385 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319431E17 

Seg1_comp_5__Extra_1 Seg1_comp_5__Extra_0 -27.69231 4.230769 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319431E17 

Seg1_comp_5__Extra_2 Seg1_comp_5__Extra_1 -29.53846 2.846154 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319534E17 

Seg1_comp_5__Extra_3 Seg1_comp_5__Extra_2 -31.38462 1.461539 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319438E17 

Seg1_comp_5__Extra_4 Seg1_comp_5__Extra_3 -33.23077 0.07692289 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319562E17 

Seg1_comp_5__Extra_5 Seg1_comp_5__Extra_4 -35.07692 -1.307692 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.031939E17 

Seg1_comp_5__Extra_6 Seg1_comp_5__Extra_5 -36.92308 -2.692308 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg1_comp_5__Extra_7 Seg1_comp_5__Extra_6 -38.76923 -4.076923 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319383E17 

Seg1_comp_5__Extra_8 Seg1_comp_5__Extra_7 -40.61539 -5.461539 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg1_comp_5__Extra_9 Seg1_comp_5__Extra_8 -42.46154 -6.846154 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319596E17 

Seg1_comp_5__Extra_10 Seg1_comp_5__Extra_9 -44.30769 -8.230769 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319383E17 

Seg1_comp_5__Extra_11 Seg1_comp_5__Extra_10 -46.15385 -9.615384 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319486E17 

Seg1_comp_5 Seg1_comp_5__Extra_11 -48 -11 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1865483743 -7.0319465E17 

Seg0_comp_4__Extra_0 Seg1_comp_1 0 23.61539 1.846154 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4__Extra_1 Seg0_comp_4__Extra_0 0 22.23077 3.692308 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4__Extra_2 Seg0_comp_4__Extra_1 0 20.84616 5.538462 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319472E17 

Seg0_comp_4__Extra_3 Seg0_comp_4__Extra_2 0 19.46154 7.384616 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4__Extra_4 Seg0_comp_4__Extra_3 0 18.07692 9.230769 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319452E17 

Seg0_comp_4__Extra_5 Seg0_comp_4__Extra_4 0 16.69231 11.07692 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4__Extra_6 Seg0_comp_4__Extra_5 0 15.30769 12.92308 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319431E17 

Seg0_comp_4__Extra_7 Seg0_comp_4__Extra_6 0 13.92308 14.76923 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4__Extra_8 Seg0_comp_4__Extra_7 0 12.53846 16.61539 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319486E17 

Seg0_comp_4__Extra_9 Seg0_comp_4__Extra_8 0 11.15385 18.46154 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4__Extra_10 Seg0_comp_4__Extra_9 0 9.769231 20.30769 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319438E17 

Seg0_comp_4__Extra_11 Seg0_comp_4__Extra_10 0 8.384615 22.15385 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_4 Seg0_comp_4__Extra_11 0 7 24 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319486E17 

Seg1_comp_4__Extra_0 Seg0_comp_4 0 5.615385 25.84616 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319431E17 

Seg1_comp_4__Extra_1 Seg1_comp_4__Extra_0 0 4.230769 27.69231 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319431E17 

Seg1_comp_4__Extra_2 Seg1_comp_4__Extra_1 0 2.846154 29.53846 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319534E17 

Seg1_comp_4__Extra_3 Seg1_comp_4__Extra_2 0 1.461539 31.38462 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319438E17 

Seg1_comp_4__Extra_4 Seg1_comp_4__Extra_3 0 0.07692289 33.23077 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319562E17 

Seg1_comp_4__Extra_5 Seg1_comp_4__Extra_4 0 -1.307692 35.07692 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.031939E17 

Seg1_comp_4__Extra_6 Seg1_comp_4__Extra_5 0 -2.692308 36.92308 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg1_comp_4__Extra_7 Seg1_comp_4__Extra_6 0 -4.076923 38.76923 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319383E17 

Seg1_comp_4__Extra_8 Seg1_comp_4__Extra_7 0 -5.461539 40.61539 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg1_comp_4__Extra_9 Seg1_comp_4__Extra_8 0 -6.846154 42.46154 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319596E17 

Seg1_comp_4__Extra_10 Seg1_comp_4__Extra_9 0 -8.230769 44.30769 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319383E17 

Seg1_comp_4__Extra_11 Seg1_comp_4__Extra_10 0 -9.615384 46.15385 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319486E17 

Seg1_comp_4 Seg1_comp_4__Extra_11 0 -11 48 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_0 Seg1_comp_1 1.846154 23.61539 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_1 Seg0_comp_3__Extra_0 3.692308 22.23077 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_2 Seg0_comp_3__Extra_1 5.538462 20.84616 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319472E17 

Seg0_comp_3__Extra_3 Seg0_comp_3__Extra_2 7.384616 19.46154 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_4 Seg0_comp_3__Extra_3 9.230769 18.07692 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319452E17 

Seg0_comp_3__Extra_5 Seg0_comp_3__Extra_4 11.07692 16.69231 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_6 Seg0_comp_3__Extra_5 12.92308 15.30769 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319431E17 

Seg0_comp_3__Extra_7 Seg0_comp_3__Extra_6 14.76923 13.92308 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_8 Seg0_comp_3__Extra_7 16.61539 12.53846 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319486E17 

Seg0_comp_3__Extra_9 Seg0_comp_3__Extra_8 18.46154 11.15385 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3__Extra_10 Seg0_comp_3__Extra_9 20.30769 9.769231 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319438E17 

Seg0_comp_3__Extra_11 Seg0_comp_3__Extra_10 22.15385 8.384615 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg0_comp_3 Seg0_comp_3__Extra_11 24 7 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319486E17 

Seg1_comp_3__Extra_0 Seg0_comp_3 25.84616 5.615385 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319431E17 

Seg1_comp_3__Extra_1 Seg1_comp_3__Extra_0 27.69231 4.230769 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319431E17 

Seg1_comp_3__Extra_2 Seg1_comp_3__Extra_1 29.53846 2.846154 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319534E17 

Seg1_comp_3__Extra_3 Seg1_comp_3__Extra_2 31.38462 1.461539 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319438E17 

Seg1_comp_3__Extra_4 Seg1_comp_3__Extra_3 33.23077 0.07692289 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319562E17 

Seg1_comp_3__Extra_5 Seg1_comp_3__Extra_4 35.07692 -1.307692 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.031939E17 

Seg1_comp_3__Extra_6 Seg1_comp_3__Extra_5 36.92308 -2.692308 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg1_comp_3__Extra_7 Seg1_comp_3__Extra_6 38.76923 -4.076923 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319383E17 

Seg1_comp_3__Extra_8 Seg1_comp_3__Extra_7 40.61539 -5.461539 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

Seg1_comp_3__Extra_9 Seg1_comp_3__Extra_8 42.46154 -6.846154 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319596E17 

Seg1_comp_3__Extra_10 Seg1_comp_3__Extra_9 44.30769 -8.230769 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319383E17 

Seg1_comp_3__Extra_11 Seg1_comp_3__Extra_10 46.15385 -9.615384 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319486E17 

Seg1_comp_3 Seg1_comp_3__Extra_11 48 -11 0 1.7 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -7.0319465E17 

*set_compt_param     RA 1.0
*set_compt_param     ELEAK -0.0666
*set_compt_param     RM 0.1


Seg0_comp_57__Extra_0 Seg1_comp_56 26.78571 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_1 Seg0_comp_57__Extra_0 28.57143 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_2 Seg0_comp_57__Extra_1 30.35714 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_3 Seg0_comp_57__Extra_2 32.14286 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_4 Seg0_comp_57__Extra_3 33.92857 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_5 Seg0_comp_57__Extra_4 35.71429 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_6 Seg0_comp_57__Extra_5 37.5 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_7 Seg0_comp_57__Extra_6 39.28571 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_8 Seg0_comp_57__Extra_7 41.07143 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_9 Seg0_comp_57__Extra_8 42.85714 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_10 Seg0_comp_57__Extra_9 44.64286 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_11 Seg0_comp_57__Extra_10 46.42857 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57__Extra_12 Seg0_comp_57__Extra_11 48.21428 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

Seg0_comp_57 Seg0_comp_57__Extra_12 50 0 0 1.4 naf__-2138440619 4500 ka 6 kdr 4500 km 300 

*set_compt_param     RA 2.5
*set_compt_param     ELEAK -0.0666
*set_compt_param     RM 0.33333334


Seg0_comp_36__Extra_0 Seg1_comp_35 0 103.4091 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_36__Extra_1 Seg0_comp_36__Extra_0 0 106.8182 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12950491E17 

Seg0_comp_36__Extra_2 Seg0_comp_36__Extra_1 0 110.2273 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_36__Extra_3 Seg0_comp_36__Extra_2 0 113.6364 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_36__Extra_4 Seg0_comp_36__Extra_3 0 117.0455 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_36__Extra_5 Seg0_comp_36__Extra_4 0 120.4546 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12950973E17 

Seg0_comp_36__Extra_6 Seg0_comp_36__Extra_5 0 123.8636 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12950973E17 

Seg0_comp_36__Extra_7 Seg0_comp_36__Extra_6 0 127.2727 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_36__Extra_8 Seg0_comp_36__Extra_7 0 130.6818 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12950491E17 

Seg0_comp_36__Extra_9 Seg0_comp_36__Extra_8 0 134.0909 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_36 Seg0_comp_36__Extra_9 0 137.5 0 3.8 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -2.12951436E17 

Seg0_comp_12__Extra_0 Seg1_comp_35 2 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_1 Seg0_comp_12__Extra_0 4 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_2 Seg0_comp_12__Extra_1 6 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_3 Seg0_comp_12__Extra_2 8 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_4 Seg0_comp_12__Extra_3 10 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_5 Seg0_comp_12__Extra_4 12 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_6 Seg0_comp_12__Extra_5 14 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_7 Seg0_comp_12__Extra_6 16 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_8 Seg0_comp_12__Extra_7 18 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_9 Seg0_comp_12__Extra_8 20 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_10 Seg0_comp_12__Extra_9 22 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_11 Seg0_comp_12__Extra_10 24 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_12 Seg0_comp_12__Extra_11 26 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12__Extra_13 Seg0_comp_12__Extra_12 28 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_12 Seg0_comp_12__Extra_13 30 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_0 Seg1_comp_35 -2 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_1 Seg0_comp_7__Extra_0 -4 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_2 Seg0_comp_7__Extra_1 -6 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_3 Seg0_comp_7__Extra_2 -8 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_4 Seg0_comp_7__Extra_3 -10 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_5 Seg0_comp_7__Extra_4 -12 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_6 Seg0_comp_7__Extra_5 -14 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_7 Seg0_comp_7__Extra_6 -16 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_8 Seg0_comp_7__Extra_7 -18 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_9 Seg0_comp_7__Extra_8 -20 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_10 Seg0_comp_7__Extra_9 -22 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_11 Seg0_comp_7__Extra_10 -24 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_12 Seg0_comp_7__Extra_11 -26 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7__Extra_13 Seg0_comp_7__Extra_12 -28 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

Seg0_comp_7 Seg0_comp_7__Extra_13 -30 100 0 1.24 naf__-2138440619 1875 ar__218603037 2 cal 3.2 cat 2 k2 10 ka 160 kahp_deeppyr 4 kc 120 kdr 1500 km 75 nap 1 cad__-1849377615 -1.11237371E18 

